### ISSUE TITLE
Audit dryrun to confirm it does nothing

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/twolevel_ants_dbm#40]
Currently looks like it creates directories, and looks like it doesn't print the jacobian blurring steps and crashes instead:

```
Blurring Jacobians
Traceback (most recent call last):
  File "/data/chamal/projects/gabriel/src/twolevel_dbm/twolevel_dbm.py", line 705, in <module>
    main()
  File "/data/chamal/projects/gabriel/src/twolevel_dbm/twolevel_dbm.py", line 699, in main
    firstlevel(inputs, args)
  File "/data/chamal/projects/gabriel/src/twolevel_dbm/twolevel_dbm.py", line 197, in firstlevel
    secondlevel(imagelist, args, secondlevel=True)
  File "/data/chamal/projects/gabriel/src/twolevel_dbm/twolevel_dbm.py", line 483, in secondlevel
    for blur in args.jacobian_sigmas:
TypeError: 'NoneType' object is not iterable

```

**Comment by gdevenyi** [comment]
Dryrun fixed up by 7de0602f1db88de2a0cad4f096e85905a37887cb
